### ISSUE TITLE
blasr error message during alignment stage

### ISSUE THREAD

**Issue by rozaimirazali** [EichlerLab/smrtsv2#10]
This is how the align/bam/log/ directory looks like:

> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 309 Feb 18 18:07 2.log
> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 309 Feb 18 21:31 4.log
> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 309 Feb 19 01:40 8.log
> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 309 Feb 19 06:00 6.log
> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 309 Feb 19 09:46 5.log
> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 309 Feb 19 13:48 1.log
> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 309 Feb 19 18:15 7.log
> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 308 Feb 19 19:51 9.log
> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 309 Feb 19 23:14 3.log
> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 308 Feb 20 00:24 0.log
> -rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 132 Feb 20 00:24 28.log

All the *.log files showed no errors except for 28.log, which shows the following error message:

> Aligning batch 28...
> [INFO] 2019-02-20T00:24:27 [blasr] started.
> Error, you must provide at least one reads file and a genome file.

I don't understand why it is unable to use the provided reads and genome files. For example, in 0.log i did not get the above error message but this one instead:

> Aligning batch 0...
> [INFO] 2019-02-19T23:14:54 [blasr] started.
> [INFO] 2019-02-20T00:04:23 [blasr] ended.
> Sorting...
> [bam_sort_core] merging from 4 files and 1 in-memory blocks...
> Indexing...
> Compressing unaligned reads...
> Cleaning temp "/gpfs/projects/SDR_gref_ymokrab/sv/analysis/tmp/aln_align_batch_0"...
> 

My command was: smrtsv.py --tempdir ../tmp --verbose --log log.txt run --batches 32 --threads 32 GRCh37.fa multi_runs.fofn

**Comment by rozaimirazali** [comment]
I found the reason for this error. There are 10 subreads bam files but the --batches is set at 32. It's a typo. 32 was meant for the number of threads and not batches.

**Comment by paudano** [comment]
The number of batches can be far less or far more than the number of input files. It should not cause this error. If it did, then I should fix something in SMRT-SV.

**Comment by rozaimirazali** [comment]
I am re-running it with --batches equal to the number of bams. will let you know of the outcome
