### ISSUE TITLE
Using nanopore data

### ISSUE THREAD

**Issue by wdecoster** [EichlerLab/smrtsv2#11]
Hi,

I'd like to try smrtsv2 using Nanopore PromethION data, but it seems to run in some trouble. I'm using an (aligned) bam as input (I realize typically an unaligned bam would be used), and receive the following error in the align/bam/log/0.log file: 

```
Aligning batch 0...
[INFO] 2019-02-26T14:05:10 [blasr] started.
terminate called after throwing an instance of 'std::runtime_error'
  what():  malformed record name
```

Do you have any suggestions?

Cheers,
Wouter

**Comment by paudano** [comment]
The tools within the pipeline are pretty PacBio specific, so it will not work with Oxford (ONT) data.

If you want to try to get it working, there are equivalent tools that will handle ONT data. For example, you could replace BLASR with Minimap and Arrow with Nanopolish. Once it gets through alignments and assembly, I think most of the variant calling steps would complete. There may be some pipeline code that needs to be modified, but I would expect most of it to work.

If I have time, I may update the pipeline for PacBio and ONT, but this is not something I can commit to right now.

**Comment by wdecoster** [comment]
Thanks for the suggestions, I'll see if I can figure it out.
