### ISSUE TITLE
Failed at align step

### ISSUE THREAD

**Issue by bioysu** [EichlerLab/smrtsv2#13]
I tried to run smrtsv2 with PacBio reads from yeast following tutorial:
/pfs1/liuguanghui/suyao/tools/smrtsv2/smrtsv index /pfs1/liuguanghui/suyao/data/UCSC/sacCer3/chromosomes/sacCer3.fa
/pfs1/liuguanghui/suyao/tools/smrtsv2/smrtsv align /pfs1/liuguanghui/suyao/tools/smrtsv2/test_yeast2/reads2.fofn
here is the output:
![default](https://user-images.githubusercontent.com/7274431/53431577-c2570b80-3a2b-11e9-8bab-a18c32b4480c.png)
here is the log file in align/bam/log
![default](https://user-images.githubusercontent.com/7274431/53431696-fd593f00-3a2b-11e9-99ad-a66dfbadc25c.png)

Could you tell me how to fix the problem?

**Comment by RSherman15** [comment]
I had this problem as well; see issue #6. Downgrading hdf5 in the pacbio conda environment to 1.10.3 to 1.10.2 fixed it.

**Comment by paudano** [comment]
Thanks @RSherman15. The build system in `dep` now installs this version as well. You might have cloned the repository before that change was pushed. You might want to pull changes and rebuild `dep` (`make clean` and `make`).

I am closing for now, but let me know if this doesn't fix the problem.

**Comment by bioysu** [comment]
The align step is OK now.
