### ISSUE TITLE
Rerunning specific batches

### ISSUE THREAD

**Issue by RSherman15** [EichlerLab/smrtsv2#14]
blasr seems to have failed on a particular batch after aligning almost all of the batches successfully. Is there a good way to re-run only specific batch numbers? It looks like perhaps I could manually change ALIGN_BATCH_LIST in rules/align.snakefile as well as have it not re-run the aln_assign_batches rule, but I'm hoping maybe there's an easier way to do this than modifying the codebase itself?

**Comment by paudano** [comment]
Yes, just re-run SMRT-SV, and it will attempt to re-assemble anything it did not finish without re-running ones that did. Don't alter anything in the code or in files.

I have been allowing it to try assembling a region twice. There are a handful of regions over centromeres that do not assemble. For those, I'll just `touch` the output BAM file (and then remove or rename `.snakemake` so it doesn't try to re-run incomplete rules) and then restart the pipeline.
