### ISSUE TITLE
Killed job locked folder

### ISSUE THREAD

**Issue by RSherman15** [EichlerLab/smrtsv2#18]
I killed a detect run which gave an error, but continued to hang, and now I get the following error:

```
Detecting variant signatures
Building DAG of jobs...
Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:
/work-zfs/mschatz1/rsherman/smrtSVRuns
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be removed with the --unlock argument.
```

However, --unlock is not a recognized argument (either globally of smrtsv or of detect). I tried removing the whole detect folder, and still get the same error. How can I unlock the folder?

**Comment by RSherman15** [comment]
As a temporary fix I added `--unlock` into line 137 of `smrtsvrunner.py`; that seemed to unlock the folder (and then did not actually run the detect command) so that I was then able to restart the run. Might be nice to add some way to do this from calling `smrtsv`, though.

**Comment by paudano** [comment]
You can also just remove `.snakemake/locks/*`. I might add an option or just document that.

**Comment by bioabuliu** [comment]
Just need to add `--unlock` after your command, then U can resart your run!
