### ISSUE TITLE
Do smrtsv2 have resume capability?

### ISSUE THREAD

**Issue by rozaimirazali** [EichlerLab/smrtsv2#19]
Hi. Just wondering if smrtsv2 has resume capability?

For example, I am having a problem at a specific point in the Detect stage. If I re-run using the following command:

`smrtsv align/alignments.fofn detect
`
does it resume from the beginning of the Detect stage or the last point where I had encountered error previously?

**Comment by paudano** [comment]
It will pick up at the point where it left off in the detect stage. It will only re-run a rule if the rule did not complete, it's output is missing (and needed), or if there is a newer file upstream.
