### ISSUE TITLE
Unable to run 'index' stage of pipeline

### ISSUE THREAD

**Issue by ggstatgen** [EichlerLab/smrtsv2#2]
Hi,

I'm attempting to run the full pipeline on some pacbio data and have stumbled into an error in the first stage, the indexing of the reference genome.

I have followed your readme instructions and am running the python code in an empty directory, as follows

`python ${CODEPATH}/smrtsv.py index ${REFPATH}/hg38.fa`

This returns the following STDOUT output

```
reparing reference                 
localrules directive specifies rules that are not present in the Snakefile:
        ref_run
                                                                                            
Building DAG of jobs...                                                                                                                                                                   Using shell: /bin/bash                                                                                                                                               
Provided cores: 1                                                                                         
Rules claiming more threads will be scaled down.                                                            
Job counts:                                                                     
        count   jobs    
        1       ref_all                  
        1       ref_make_ctab                                       
        1       ref_make_sizes                                                                                 
        3           
[Wed Jan 23 14:25:07 2019]                                         
rule ref_make_ctab:                                                                                                                              
    input: reference/ref.fasta
    output: reference/ref.fasta.ctab
    jobid: 3

/bin/bash: PrintTupleCountTable: command not found
[Wed Jan 23 14:25:07 2019]
Error in rule ref_make_ctab:
    jobid: 3
    output: reference/ref.fasta.ctab

RuleException:
CalledProcessError in line 69 of ${CODEPATH}/rules/reference.snakefile:
Command ' set -euo pipefail;  if [ "True" = "True" -a -f ${REFPATH}/hg38.fa.ctab ]; then ln -sf ${REFPATH}/hg38.fa.ctab reference/
ref.fasta.ctab; else PrintTupleCountTable reference/ref.fasta > reference/ref.fasta.ctab; chmod a-w reference/ref.fasta.ctab; fi 

 returned non-zero exit status 127.
  File "${CODEPATH}/rules/reference.snakefile", line 69, in __rule_ref_make_ctab
  File "${CODEPATH}/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job ref_make_ctab since they might be corrupted:
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

So it appears the code can't find a `PrintTupleCountTable` executable - is that part of an non annotated prerequisite library? There is a config.sh file in the release directory, however this seems create environment variables which point to obsolete or non existent resources within the release.

Could you provide information on what kind of pre-requisite software is required to run the full pipeline and if any special environmental variables have to be set? Thanks in advance!

**Comment by paudano** [comment]
I forgot to include instructions for building dependencies in `README.md`. I just added it.

```
cd dep
make
```

This will build the SMRT-SV dependencies, which includes `PrintTupleCountTable`.

I also removed `config.sh`. That was a vestige of SMRT-SV v1. Thanks!

Let me know if this works for you.

**Comment by ggstatgen** [comment]
Hi thanks for this. I have tried this and unfortunately it terminates with the following error

```
mkdir -p bin                                                                                                                                                                              
/smrtsv2/dep/conda/build/envs/tools/bin/g++ \                                                                                                                 
        -std=c++11 -I/smrtsv2/dep/conda/build/envs/tools/include \                                                                                            
        -I/smrtsv2/dep/conda/build/envs/pacbio/include \                                                                                                      
        -I/smrtsv2/dep/conda/build/envs/pacbio/include/libblasr \                                                                                             
        -L/smrtsv2/dep/conda/build/envs/tools/lib \                                                                                                           
        -Wl,-rpath=/smrtsv2/dep/conda/build/envs/tools/lib \                                                                                                  
        -L/smrtsv2/dep/conda/build/envs/pacbio/lib \                                                                                                          
        -Wl,-rpath=/smrtsv2/dep/conda/build/envs/pacbio/lib \                                                                                                 
        -lblasr \                                                                                                                                                                         
        -o bin/PrintTupleCountTable \                                                                                                                                                     
        blasr/extrautils/PrintTupleCountTable.cpp                                                                                                                                         
/smrtsv2/dep/conda/build/envs/pacbio/lib/libblasr.so: undefined reference to `H5::H5Location::getObjnameByIdx(unsigned long long) const'                      
/smrtsv2/dep/conda/build/envs/pacbio/lib/libblasr.so: undefined reference to `H5::H5Location::createGroup(std::string const&, unsigned long) const'           
/smrtsv2/dep/conda/build/envs/pacbio/lib/libblasr.so: undefined reference to `H5::Attribute::read(H5::DataType const&, std::string&) const'                   
/smrtsv2/dep/conda/build/envs/pacbio/lib/libblasr.so: undefined reference to `H5::Exception::getDetailMsg() const'                                            
/smrtsv2/dep/conda/build/envs/pacbio/lib/libblasr.so: undefined reference to `H5::Attribute::write(H5::DataType const&, std::string const&) const'            
/smrtsv2/dep/conda/build/envs/pacbio/lib/libblasr.so: undefined reference to `H5::H5Object::iterateAttrs(void (*)(H5::H5Object&, std::string, void*), unsigned
 int*, void*)'                                                                                                                                                                            
/smrtsv2/dep/conda/build/envs/pacbio/lib/libhdf5_cpp.so.103: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'                      
collect2: error: ld returned 1 exit status                                                                                                                                                
make[1]: *** [Makefile:9: bin/PrintTupleCountTable] Error 1                                                                                                                               
make[1]: Leaving directory '/smrtsv2/dep/blasr_extrautil'                                                                                                     
make: *** [Makefile:36: install_flags/dep_blasr-extrautil_build] Error 2
```
I wonder if this is about missing hfd5 libraries.

As a separate note, It seems your makefile above downloads and builds an entire miniconda sandbox with both python2 and python3 and a lot of tools. Are these all required to run the pipeline or is there a minimal set of tools you'd recommend installing? 

Just asking because I already have a miniconda sandbox up and running with basic long read/genomics analysis tools installed (canu, ngmlr, etc) and was wondering if it would be simpler to install any specific ones needed by smrtsv2.

For instance, I found `printTupleCountTable` is part of Mark Chaisson's modified `blasr` package available  here

[https://github.com/mchaisso/blasr](https://github.com/mchaisso/blasr)

I've installed that and got the executable up and running - should I go down this route and install on a per need basis or you'd recommend not? Thanks!

**Comment by ggstatgen** [comment]
Hi again,

To follow up on the issue above, 

` /smrtsv2/dep/conda/build/envs/pacbio/lib/libhdf5_cpp.so.103`

I think it might be due to blasr_extrautil complaining that the h5py/hdf5 c++ libraries are too recent. I can't find an explicit install instruction in your makefiles for these, so I'm going to assume conda installs the most recent available automatically (I think it's the 1.10.3) and these don't play well with blasr/blasr_extrautils.

As a test - is there any way to force installation of older hdf5 libraries in your dep/make miniconda sandbox? I found in the past that blasr works fine with the 1.8.21 release if that's of help

**Comment by paudano** [comment]
A)
The system I built this on must have had hdf5 libraries installed in the system library paths. I am able to replicate the problem on another machine, and I am working on it now.

B)
Yes, SMRT-SV depends on everything build in the `dep` directory. There is a mix of python2 and python3 code, and PacBio tools are installed in their own environment to resolve dependency version conflicts with other tools.

You can use pre-compiled tools, but you will have to make adjustments. For example, `printTupleCountTable` is now `PrintTupleCountTable` in the current PacBio distributions. The format of command-line options in BLASR has changed since Mark's fork, and so that would have to change too. It should be far easier to use the updated tools than to modify SMRT-SV for older versions.

**Comment by paudano** [comment]
I think this may be cause by incompatible ABI versions in the libraries the build system is trying to link, and using the latest versions of GCC dosen't seem to resolve it.

I am going to see if PacBio will add `PrintTupleCountTable` to their BLASR conda build (https://github.com/PacificBiosciences/pbbioconda/issues/80).

It's not strictly required, but it does speed things up. I am probably going to pull it from the pipeline, and if PacBio adds it to the blasr conda package, I might add it back in a later version.

**Comment by paudano** [comment]
I removed `PrintTupleCountTable` and pushed the change. It's too problematic to keep in the pipeline. I tested, and all dependencies were built.

If you wanted to generate the `.ctab` file once to speed up alignments, you could run `index` and then generate it with your own copy of `PrintTupleCountTable`. This should help initial read mapping and mapping contigs back to the reference.

Note that I also removed `RepeatMasker` from the build because the conda install for it is also not working right (it's used in the final calling stages). You'll need RepeatMasker in your path. In some future version, this will be removed entirely.

I am closing this case, but feel free to re-open it if you still have problems after pulling a new copy of the repository.

**Comment by ggstatgen** [comment]
Hi again,

I have checked out the updated pipeline and things seem to be running smoothly so far, so thanks for your help on this!

However, I was attempting to run the full pipeline on a separate dataset from scratch and have stumbled into an issue. The `index` stage seems to run fine. However, it does not generate a `.ctab` file from the reference fasta anymore. It seems you commented the following in `rules/reference.snakefile`:

```
# ref_make_ctab
#
# Count k-mers in the reference.
#
# Note: Removed unless PacBio adds it to the blasr conda module (https://github.com/EichlerLab/smrtsv2/issues/2)
#rule ref_make_ctab:
#    input:
#        ref_fa='reference/ref.fasta'
#    output:
#        ref_ctab='reference/ref.fasta.ctab'
#    shell:
#        """if [ "{LINK_INDEX}" = "True" -a -f {REFERENCE}.ctab ]; then """
#            """ln -sf {REFERENCE}.ctab {output.ref_ctab}; """
#        """else """
#            """PrintTupleCountTable {input.ref_fa} > {output.ref_ctab}; """
#            """chmod a-w {output.ref_ctab}; """
#        """fi"""
```

The problem is that the following stage, `assemble`, now fails as follows

```
>smrtsv.py align --batches 2 --threads 50 reads.fofn
Aligning sequence reads
Building DAG of jobs...
MissingInputException in line 44 of <CODE>/smrtsv2/rules/align.snakefile:
Missing input files for rule aln_align_batch:
reference/ref.fasta.ctab
```

Apologies if I'm missing something obvious.

**Comment by paudano** [comment]
No, I missed something obvious. Rules in align and assemble still had it as a dependency . Just pushed an update to  fix that.

**Comment by ggstatgen** [comment]
Fantastic thanks!
