### ISSUE TITLE
Bus error during detect_gaps_search

### ISSUE THREAD

**Issue by rozaimirazali** [EichlerLab/smrtsv2#20]
Hi. I am getting a Bus error message during the Detect stage.

> [Wed Mar  6 07:23:10 2019]
> Finished job 16.
> 16 of 72 steps (22%) done
> 
> [Wed Mar  6 07:23:10 2019]
> rule detect_gaps_search:
>     input: align/bam/4.bam, reference/ref.fasta, reference/ref.fasta.fai
>     output: detect/gaps/batch/4_all.bed
>     log: detect/gaps/batch/log/4.log
>     jobid: 62
>     wildcards: batch_id=4
> 
> /usr/bin/bash: line 1: 219513 Broken pipe             samtools view -F 0x4 -q 30 align/bam/4.bam
>      219514 Bus error               | python2 /gpfs/software/genomics/smrtsv2/smrtsv2/scripts/PrintGaps.py reference/ref.fasta /dev/stdin --condense 20 > detect/gaps/batch/4_all.bed 2> detect/gaps/batch/log/4.log
> /gpfs/home/rmohamadrazali/.lsbatch/1551709440.220922: line 8: 284704 Bus error               smrtsv.py --tempdir tmp --verbose --log log.txt run --batches 10 --threads 32 GRCh37.fa multi_runs.fofn

When I look at the log inside detect/gaps/batch/log/ , the file size are all 0 bytes.

-rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 0 Mar  5 19:36 7.log
-rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 0 Mar  5 21:37 6.log
-rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 0 Mar  5 23:45 8.log
-rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 0 Mar  6 01:27 2.log
-rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 0 Mar  6 03:27 1.log
-rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 0 Mar  6 05:34 5.log
-rw-rw-r-- 1 rmohamadrazali SDR_gref_ymokrab 0 Mar  6 07:23 4.log

**Comment by paudano** [comment]
I have only seen "Bus error" when the system kills one process in a command pipeline (cmd1 | cmd2 | cmd3 ...). If you are running it through a cluster system, check the job history to see what the runtime and memory usage was and if it was killed. If you are running it on a standalone host, check memory utilization, temp space, etc.
