### ISSUE TITLE
[input file ]  smrtsv.py detect parameter

### ISSUE THREAD

**Issue by Xuelei-Dai** [EichlerLab/smrtsv2#23]
Hi Peter
I have stuck in detecting SV using your software smrtsv2. The README is quite ambiguous, especially the input file parameter. I am wondering how could I input a bam file with detect command. And could you please providing me any detailed handbook about how to run correctly in every step. 
Thanks in advance.

**Comment by paudano** [comment]
In `README.md`, search for "To run all steps:".

You don't need to run each step individually. You don't input a BAM into "detect". It is input into "align", and detect gets what it needs from the "align" output. Just use the "run" command, it does everything.
