### ISSUE TITLE
Error in rule detect_stops_count_per_bin

### ISSUE THREAD

**Issue by lamevan** [EichlerLab/smrtsv2#27]
Hi,I run the following command...and the reference genome use UCSC name.

smrtsv --tempdir /home/lamevan/temp --jobs 4 run --batches 20  --threads 8 all.chrs.con input.fofn

Could you please explain why I am getting error here?

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.

**[Deleted by paudano - moved to attachment]**

[detect_run_output.txt](https://github.com/EichlerLab/smrtsv2/files/3054943/detect_run_output.txt)

[Sun Apr  7 22:27:15 2019]
rule detect_stops_count_per_bin:
    input: detect/stops/hardstops/hardstop_breakpoints.bed, detect/stops/hardstop_bins.bed
    output: detect/stops/hardstops/hardstop_breakpoints_binned.bed
    jobid: 32

Error: Invalid record in file detect/stops/hardstops/hardstop_breakpoints.bed. Record is 
Chr2	-1	0	m150315_201009_42208_c100768742550000001823166207301516_s1_p0/72453/19969_40060	19500	right
[Sun Apr  7 22:27:16 2019]
Error in rule detect_stops_count_per_bin:
    jobid: 32
    output: detect/stops/hardstops/hardstop_breakpoints_binned.bed

RuleException:
CalledProcessError in line 300 of /home/linpeifan/smrtsv2/smrtsv2-master/rules/detect.snakefile:
Command ' set -euo pipefail;  bedtools intersect -a detect/stops/hardstop_bins.bed -b detect/stops/hardstops/hardstop_breakpoints.bed -sorted -c >detect/stops/hardstops/hardstop_breakpoints_binned.bed ' returned non-zero exit status 1.
  File "/home/linpeifan/smrtsv2/smrtsv2-master/rules/detect.snakefile", line 300, in __rule_detect_stops_count_per_bin
  File "/home/linpeifan/smrtsv2/smrtsv2-master/dep/conda/build/envs/python3/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job detect_stops_count_per_bin since they might be corrupted:
detect/stops/hardstops/hardstop_breakpoints_binned.bed
[Sun Apr  7 22:28:41 2019]
Finished job 31.

Hi,I run the following command...and the reference genome use UCSC name.
smrtsv --tempdir /home/lamevan/temp --jobs 4 run --batches 20  --threads 8 all.chrs.con input.fofn

Could you please explain why I am getting error here?

**Comment by lamevan** [comment]
Maybe the problem occur from that i put 5 bax.h5 file into a bam file..

**Comment by paudano** [comment]
The error is pretty clear:
Error: Invalid record in file detect/stops/hardstops/hardstop_breakpoints.bed. Record is
Chr2 -1 0 m150315_201009_42208_c100768742550000001823166207301516_s1_p0/72453/19969_40060 19500 right

Can you attach `detect/stops/hardstops/hardstop.bed` and `detect/stops/hardstops/hardstop_breakpoints.bed`? Just drag-and-drop them to the reply, and github will add them as an attachment.

Are the files in `input.fofn` ".bam" or ".bax.h5" files? We have been seeing some problems running from BAX, but I have not seen this error yet.

**Comment by lamevan** [comment]
I remove the error line in bed file.it works.
thank you!

**Comment by paudano** [comment]
Ok, it would have been good to see what was causing the bug, but I'm glad it's working.
