### ISSUE TITLE
Genotyping using short reads?

### ISSUE THREAD

**Issue by holtgrewe** [EichlerLab/smrtsv2#37]
I might be missing something, but I cannot find short or Illumina reads being mentioned in the `GENOTYPE.md` file.

How could I do genotyping of variants using short-read data?

**Comment by paudano** [comment]
Sorry for taking so long to respond. My SPAM filters started marking GitHub notifications as junk.

In the first sentence of `GENOTYPE.md`, "sample alignment files (BAM/CRAM)" are the Illumina short-read samples. In the "Sample table" section, each line is one short-read sample.

If you have FASTQs, then you could place them in an unmapped BAM and run the genotyper on them.

I am updating `GENOTYPE.md` to make it a little clearer. If you have further questions, feel free to re-open this ticket.
