### ISSUE TITLE
Failure in parsing arguments

### ISSUE THREAD

**Issue by RSherman15** [EichlerLab/smrtsv2#4]
As per your README, I should be able to run:
`${SMRTSV_DIR}/smrtsv.py [index|align|detect|call|genotype|run] [options] path/to/ref.fasta path/to/reads.fofn`

I am trying to run from the detect step, as I already have aligned reads I would like to use. I have a fofn with a path to the bam file (the fofn file is a single line), and I have the reference to which the reads were aligned. However
`${SMRTSV_DIR}/smrtsv.py detect [path to ref] [path to fofn]`
yields
`smrtsv.py: error: unrecognized arguments: /data/genomes/human/GRCh38/Homo_sapiens.GRCh38.dna_sm.main_chrs.fa HG002.fofn`

The help menu does not explain the positional arguments at all, only the options, but the README seems to indicate the positional arguments are the reference, then a file of file names. Is this not correct?

**Comment by paudano** [comment]
Each command (index, align, etc) has it's own command-line options, and the detect command has no positional parameters. It relies on directory structures in the run directory created by `index` and `align` to find its input.

You can try to fake the files `detect` expects, but it might cause you more problems. It looks for `align/alignments.fofn`, which is a list of files (one per line) where each file points to `align/bam/{batch_id}.bam` (batch_id is a unique number for each line). I would just let SMRT-SV run from the beginning and generate the alignments. It would be a greater set back if you got through the assemblies and realized something was set up incorrectly and needed to be re-done. If you go down this route, I will only be able to provide very limited support.

**Comment by RSherman15** [comment]
Thanks. You may want to update your readme which states:
```
${SMRTSV_DIR}/smrtsv.py run --batches 20 --threads 8 path/to/ref.fasta path/to/reads.fofn

Each step (see above) can be run on its own by replacing run with the name of the step.
```

as this implies, to me at least, that these positional arguments can be included in any step.
