### ISSUE TITLE
Is the `Align` step required?

### ISSUE THREAD

**Issue by SHuang-Broad** [EichlerLab/smrtsv2#41]
Hi,

I am tasked running the SMRT-SV-2 algorithm and compare its performance against several long read SV callers.
Reading the read me and the publication on SMRT-SV, I am wondering if this alignment step is a required step, or can it be skipped if the PacBio (HiFi) read has already be aligned (minimap2) to the desired reference?

Thanks!
Steve

**Comment by paudano** [comment]
If you have the alignments, create a file with paths to the BAM(s):
``align/alignments.fofn``

The pipeline should pick it up from there. Let me know if you have any trouble with it.
