### ISSUE TITLE
Recommended `--exclude` BED in the detect step

### ISSUE THREAD

**Issue by SHuang-Broad** [EichlerLab/smrtsv2#42]
Hi, 

I am wondering if you have any recommendations on what should go into the BED that is fed to `--exclude` in the `detect` step.
I am thinking about segmental duplications.

Thanks!
Steve

**Comment by paudano** [comment]
I don't use this option. Instead, I run SMRT-SV with no filtering, but I'll filter the SV calls afterward. That way, I can always go back and look at what was removed, which cannot be done if it filters in SMRT-SV. If you filter segmental duplications, then you are losing too many valuable loci that long reads are capable of resolving.

I created a "low-confidence" filter on GRCh38 to remove SV calls in centromeres and peri-centromeric loci where SMRT-SV reproducibility was low (10.1016/j.cell.2018.12.019).

Filter BED:
[lc.bed.gz](https://github.com/EichlerLab/smrtsv2/files/3790472/lc.bed.gz)
