### ISSUE TITLE
Unable to compile dependencies

### ISSUE THREAD

**Issue by lcslyh** [EichlerLab/smrtsv2#45]
Hello, I'm trying to install smrtsv2, and I can't build the dependencies. I get the following error:

    PackagesNotFoundError: The following packages are not available from current channels:
    - gcc=4.8.5

Then I installed GCC 4.8.5 and tried many times, but it still reports the same error, I don't know how to solve it. The following is the complete error message:

    The following NEW packages will be INSTALLED:

      _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-main
      ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
      certifi            conda-forge/linux-64::certifi-2019.11.28-py36_0
      libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-hdf63c60_0
      ncurses            conda-forge/linux-64::ncurses-5.9-10
      openssl            conda-forge/linux-64::openssl-1.0.2t-h14c3975_0
      pip                conda-forge/linux-64::pip-19.3.1-py36_0
      python             conda-forge/linux-64::python-3.6.2-0
      readline           conda-forge/linux-64::readline-6.2-0
      setuptools         conda-forge/linux-64::setuptools-42.0.2-py36_0
      sqlite             conda-forge/linux-64::sqlite-3.13.0-1
      tk                 conda-forge/linux-64::tk-8.5.19-2
      wheel              conda-forge/linux-64::wheel-0.33.6-py36_0
      xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
      zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006

    Preparing transaction: done
    Verifying transaction: done
    Executing transaction: done
    #
    # To activate this environment, use
    #
    #     $ conda activate tools
    #
    # To deactivate an active environment, use
    #
    #     $ conda deactivate

    date > build/install_flags/env_tools_deploy
    Warning: 'defaults' already in 'channels' list, moving to the top
    Warning: 'bioconda' already in 'channels' list, moving to the top
    Warning: 'conda-forge' already in 'channels' list, moving to the top
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.

    PackagesNotFoundError: The following packages are not available from current channels:

      - gcc=4.8.5

    Current channels:

      - https://conda.anaconda.org/conda-forge/linux-64
      - https://conda.anaconda.org/conda-forge/noarch
      - https://conda.anaconda.org/bioconda/linux-64
      - https://conda.anaconda.org/bioconda/noarch
      - https://repo.anaconda.com/pkgs/main/linux-64
      - https://repo.anaconda.com/pkgs/main/noarch
      - https://repo.anaconda.com/pkgs/r/linux-64
      - https://repo.anaconda.com/pkgs/r/noarch

    To search for alternate channels that may provide the conda package you're
    looking for, navigate to

        https://anaconda.org

    and use the search bar at the top of the page.

    make[1]: *** [build/install_flags/env_tools_install] error 1
    make[1]: Leaving directory `/opt/biosoft/smrtsv2/dep/conda'
    make: *** [install_flags/dep_conda_build] error 2    

I am using Linux CentOS 6.9.

**Comment by lcslyh** [comment]
My GCC version:
![](https://tva1.sinaimg.cn/large/006tNbRwgy1g9swd5jr56j31na0j0h0l.jpg)

**Comment by eldariont** [comment]
Hi,

I hope it's okay if I chip in on this but I experienced the very same problem last week and I almost gave up on trying to install SMRTSV2. Yesterday, I gave it a new try in a completely new directory and this time `make` completed successfully without any problems. I do not have any idea what made the difference.

gcc 4.8.5 was eventually found in channel `anaconda` (see [here](https://anaconda.org/anaconda/gcc/files)). So the question is why this package cannot be found in your case (and my case of last week).

Hoping that this helps somewhat.
Best
David

**Comment by lcslyh** [comment]
Thank you very much, David！I will try it.

**Comment by lcslyh** [comment]
> Hi,
> 
> I hope it's okay if I chip in on this but I experienced the very same problem last week and I almost gave up on trying to install SMRTSV2. Yesterday, I gave it a new try in a completely new directory and this time `make` completed successfully without any problems. I do not have any idea what made the difference.
> 
> gcc 4.8.5 was eventually found in channel `anaconda` (see [here](https://anaconda.org/anaconda/gcc/files)). So the question is why this package cannot be found in your case (and my case of last week).
> 
> Hoping that this helps somewhat.
> Best
> David

Thank you very much, David！I will try it.

**Comment by paudano** [comment]
I have already updated the dependency installation process to fix this, and I am currently testing. It's looking good, so I pushed the changes as v2.0.1 (fd4f2203b8c40416ac91c3ef095348f92a5a3f91).

I'll close this for now, but if it doesn't work, you can re-open this issue.
