### ISSUE TITLE
ctab file expected for align, not generated by index

### ISSUE THREAD

**Issue by RSherman15** [EichlerLab/smrtsv2#5]
I am running the full smrtsv pipeline with smrtsv.py run [ref.fa] [reads.fofn].

The index step seems to run just fine, but then alignment seems to expect index to have produce a .ctab file, which it did not. Log output and error is below.

```
[Tue Feb  5 20:59:18 2019]
localrule ref_all:
    input: reference/ref.fasta, reference/ref.fasta.fai, reference/ref.fasta.sa, reference/ref.fasta.sizes
    jobid: 0

[Tue Feb  5 20:59:18 2019]
Finished job 0.
5 of 5 steps (100%) done
Complete log: /work-zfs/mschatz1/rsherman/smrtSVRuns/.snakemake/log/2019-02-05T195710.152975.snakemake.log
Aligning sequence reads
Building DAG of jobs...
MissingInputException in line 44 of /home-4/rsherma8@jhu.edu/bin/packages/smrtsv2/rules/align.snakefile:
Missing input files for rule aln_align_batch:
reference/ref.fasta.ctab
Failed to align reads
```

It looks like maybe the `ref_ctab='reference/ref.fasta.ctab'` line just should have been removed in the last commit that updated the ctab file handling?

**Comment by paudano** [comment]
The ctab index is not needed. I had to remove it (issue #2) because the tool could not be compiled reliably by the build process in all environments, but the alignment rule was still expecting it.
