### ISSUE TITLE
Canu v1.7 failing due to GNUplot dependency  

### ISSUE THREAD

**Issue by rorycraig337** [EichlerLab/smrtsv2#51]
Hi,

I had the same issue at install as #49, and got around this by using canu v1.7.1. However, this is crashing at the assemble stage as my environment lacks the gnuplot dependency (as far as I know, this is bypassed automatically if absent in later versions of canu). I can get around this by adding "gnuplotTested=true" as a parameter when running canu - could you possibly point me in the direction of which files/lines I need to change to run with this parameter?

Cheers,
Rory

**Comment by paudano** [comment]
I pushed a change to include this in the Canu command. Thanks! You should be able to `git pull` and run it.

If you pull the change, you don't need to modify anything, but the code is in `rules/assemble_group.snakefile` starting at line 334.

```
shell(
    """set +e; """
    """timeout {params.max_runtime} canu """
        """-pacbio-raw """
        """{input.fasta} """
        """genomeSize={genome_size} """
        """-d {canu_dir} """
        """-p asm """
        """useGrid=false """
        """gnuplotTested=true """
        """corMhapSensitivity=high """
        """corMinCoverage=2 """
        """correctedErrorRate=0.045 """  # Was errorRate=0.035
        """-pacbio-raw """
        """>{log} 2>&1; """
    """RET_CODE=$?; """
    """if [ ${{RET_CODE}} -ne 0 ]; then """
        """if [ ${{RET_CODE}} -eq 124 ]; then """
            """echo "Assembly timeout ({params.max_runtime})"; """
        """else """
            """echo "Assembly error: Return code = ${{RET_CODE}}"; """
        """fi; """
    """fi; """
)
```

Closing for now, but feel free to re-open if there is still a problem.

**Comment by paudano** [comment]
I removed "gnuplotTested=true", it was taken out in Canu 1.8. Sorry about that. See the previous post about how to fix it in your install.

**Comment by rorycraig337** [comment]
Perfect, thank you - everything now working well!
