### ISSUE TITLE
Smrtsv failed on polishing Pacbio CCS data in the assemble stage

### ISSUE THREAD

**Issue by LYC-vio** [EichlerLab/smrtsv2#57]
Hi,

Accroding to the error message from smrtsv2, Arrow algorithm only works on polishing non-CCS data (this is also mentioned [here](https://github.com/PacificBiosciences/pbbioconda/issues/195#issuecomment-533578354)). Would you please give some suggestions on using smrtsv2 on CCS datasets?

Best regards

**Comment by wharvey31** [comment]
Hello,

SMRT-SV was designed specifically with CLR reads in mind. As such, tuning and parameterization might yield incorrect results even if you were to replace the assembly and polishing steps with something like hifiasm and racon, respectively. 

If you have CCS data and want to call structural variation using assembly sequence, I would recommend first assembling with hifiasm (https://github.com/chhylp123/hifiasm) and then using PAV (https://github.com/EichlerLab/pav).

Good luck!

**Comment by paudano** [comment]
Yes, SMRT-SV is essentially end-of-life. The SMRT-SV local assembly method was very helpful at the time, but as William was saying, we have better ways using whole genome assemblies (phased or unphased). If I did take the time to update it for HiFi, I still don't think it would be a useful validation-only callset (I would use other modern variant discovery tools for that).

We most often use:
* PAV (https://github.com/EichlerLab/pav)
* pbsv (https://github.com/PacificBiosciences/pbsv)
* Sniffles (https://github.com/fritzsedlazeck/Sniffles)
* SVIM (https://github.com/eldariont/svim)
* DeepVariant (https://github.com/google/deepvariant) - smaller variants

The latest version of hifiasm has a mode to generate phased assemblies using only HiFi reads. It generates two GFA files, which you can turn into FASTA files and pipe directly into PAV or SVIM. pbsv, Sniffles, and DeepVariant are based on read alignments to the reference (no assembly step).
