### ISSUE TITLE
smrtsv2 support for ONT

### ISSUE THREAD

**Issue by prasundutta87** [EichlerLab/smrtsv2#58]
Hi,

I was wondering if smrtsv2 supports ONT reads as well in addition to PacBio.

Regards,
Prasun

**Comment by paudano** [comment]
In the assembly phase of SMRT-SV, there are polishing steps specific to PacBio CLR. The overall process could be modified for ONT, but it's not recommended.

When SMRT-SV was developed, PacBio CLR reads were much shorter (around 10 kbp) and there were significant benefits with the local-assembly approach the pipeline uses. With longer and higher-fidelity reads today, I don't think the SMRT-SV approach could compete with standard read-alignment callers like Sniffles or whole-genome assembly (e.g. flye or shasta assemblers) followed by assembly-based callers (PAV, svim-asm, or dipcall).

The technology has changed significantly enough that the SMRT-SV local-assembly approach is no longer necessary and would result in both lower sensitivity and specificity compared to modern tools.

Thank you for your interest in SMRT-SV, but we no longer recommend it.
