### ISSUE TITLE
Error during alignment - CalledProcessError in line 72 of smrtsv2/rules/align.snakefile

### ISSUE THREAD

**Issue by rozaimirazali** [EichlerLab/smrtsv2#8]
I am encountering an error at Step 4 out of 34 during the alignment stage.

The error message is not very clear. I am attaching both the stderr and the snakemake.log file.

Error file:
[smrtsv.er.txt](https://github.com/EichlerLab/smrtsv2/files/2865199/smrtsv.er.txt)

snakemake.log:
[2019-02-04T115847.899456.snakemake.log.txt](https://github.com/EichlerLab/smrtsv2/files/2865203/2019-02-04T115847.899456.snakemake.log.txt)

**Comment by paudano** [comment]
Output is sent to the log file (see "log:" in the rule output).

What is in this file?:
align/bam/log/3.log

**Comment by rozaimirazali** [comment]
The log shows the following:

> Aligning batch 3...
[INFO] 2019-02-04T16:54:13 [blasr] started.
[INFO] 2019-02-04T19:09:12 [blasr] ended.
Sorting...
[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_close] File write failed
samtools sort: failed to create temporary file "/tmp/aln_align_batch_3/3.0009.bam": No space left on device

How do I force it to use my scratch dir rather than /tmp ?

**Comment by paudano** [comment]
The `--tempdir` argument will do that.

If `--tempdir` is not set, it uses `tempfile.gettempdir()`. This function resolves the temporary directory based on environment variables and falls back to `/tmp` if none are set (See https://docs.python.org/3.7/library/tempfile.html#tempfile.gettempdir).

**Comment by rozaimirazali** [comment]
> The `--tempdir` argument will do that.
> 
> If `--tempdir` is not set, it uses `tempfile.gettempdir()`. This function resolves the temporary directory based on environment variables and falls back to `/tmp` if none are set (See https://docs.python.org/3.7/library/tempfile.html#tempfile.gettempdir).

I tried that but I am getting this error message in my stderr file:

> usage: smrtsv.py [-h] [--dryrun] [--distribute] [--jobs JOBS]
                 [--tempdir TEMPDIR] [--verbose]
                 [--cluster-config CLUSTER_CONFIG]
                 [--cluster-params CLUSTER_PARAMS] [--drmaalib DRMAALIB]
                 [--job-prefix JOB_PREFIX] [--keep-going] [--nt] [--log LOG]
                 [--wait-time WAIT_TIME]
                 {index,align,detect,assemble,call,run,genotype} ...
smrtsv.py: error: unrecognized arguments: --tempdir --verbose --log GRCh37.fa multi_runs.fofn

My command is:

bsub -q qgp -P assembly -m JRNAS1 -R span[hosts=1] -e smrtsv.er -o smrtsv.o -J smrtsv -n 32 "smrtsv.py run --tempdir ../tmp --verbose --batches 32 --threads 32 --log log.txt GRCh37.fa multi_runs.fofn"

**Comment by rozaimirazali** [comment]
I tried that but I am getting this error message in my stderr file:

> usage: smrtsv.py [-h] [--dryrun] [--distribute] [--jobs JOBS]
> [--tempdir TEMPDIR] [--verbose]
> [--cluster-config CLUSTER_CONFIG]
> [--cluster-params CLUSTER_PARAMS] [--drmaalib DRMAALIB]
> [--job-prefix JOB_PREFIX] [--keep-going] [--nt] [--log LOG]
> [--wait-time WAIT_TIME]
> {index,align,detect,assemble,call,run,genotype} ...
> smrtsv.py: error: unrecognized arguments: --tempdir --verbose --log
GRCh37.fa multi_runs.fofn

My command is:

bsub -q qgp -P assembly -m JRNAS1 -R span[hosts=1] -e smrtsv.er -o smrtsv.o
-J smrtsv -n 32 "smrtsv.py run --tempdir ../tmp --verbose --batches 32
--threads 32 --log log.txt GRCh37.fa multi_runs.fofn"
